CREATE TABLE USERS (
    USER_ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(200) NOT NULL,
    ROLE VARCHAR(20) NOT NULL
);

CREATE TABLE LIBRARY_ITEMS (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITLE VARCHAR(150) NOT NULL,
    AUTHOR VARCHAR(100) NOT NULL,
    GENRE VARCHAR(30) NOT NULL,
    TYPE VARCHAR(20) NOT NULL,
    LANGUAGE VARCHAR(30) NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    AVAILABILITY BOOLEAN NOT NULL
);

CREATE TABLE BORROWED_BOOKS (
    BORROW_ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID INTEGER NOT NULL,
    BOOK_ID INTEGER NOT NULL,
    BORROW_DATE DATE NOT NULL,
    RETURN_DUE_DATE DATE NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    CONSTRAINT FK_BORROW_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_BORROW_BOOK FOREIGN KEY (BOOK_ID) REFERENCES LIBRARY_ITEMS(ID)
);

CREATE TABLE PURCHASE (
    PURCHASE_ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID INTEGER NOT NULL,
    PURCHASE_DATE DATE NOT NULL,
    PAYMENT_METHOD VARCHAR(20) NOT NULL,
    PAYMENT_STATUS VARCHAR(20) NOT NULL,
    TOTAL_COST DECIMAL(10,2) NOT NULL,
    CONSTRAINT FK_PURCHASE_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

ALTER TABLE USERS
ADD CONSTRAINT CHK_ROLE
CHECK (ROLE IN ('manager','employee','customer'));

ALTER TABLE PURCHASE
ADD CONSTRAINT CHK_PAYMENT_STATUS
CHECK (PAYMENT_STATUS IN ('success','failed'));

ALTER TABLE PURCHASE
ADD CONSTRAINT CHK_PAYMENT_METHOD
CHECK (PAYMENT_METHOD IN ('Visa','MasterCard','Mada','PayPal'));